import { Topic } from "./types";

export const tourism: Topic = {
  slug: "tourism",
  name: "How Can Tourism Be Managed Effectively?",
  nameZh: "\u65c5\u6e38\u5982\u4f55\u5f97\u5230\u6709\u6548\u7ba1\u7406\uff1f",
  subject: "Geography",
  subjectZh: "\u5730\u7406",
  year: "Year 8",
  lessons: [

    /* ========== Lesson 1 ========== */
    {
      num: 1,
      badge: "T",
      title: "How does tourism impact different people?",
      titleZh: "\u65c5\u6e38\u5982\u4f55\u5f71\u54cd\u4e0d\u540c\u7fa4\u4f53\uff1f",
      subtitle: "Tourism brings jobs, income, and cultural exchange \u2014 but its impacts are not the same for everyone.",
      subtitleZh: "\u65c5\u6e38\u5e26\u6765\u5c31\u4e1a\u673a\u4f1a\u3001\u6536\u5165\u548c\u6587\u5316\u4ea4\u6d41\u2014\u2014\u4f46\u5176\u5f71\u54cd\u5e76\u975e\u5bf9\u6bcf\u4e2a\u4eba\u90fd\u76f8\u540c\u3002",
      sections: [
        {
          type: "goals",
          items: [
            { en: "I can define tourism and identify different types of tourism.", zh: "\u6211\u80fd\u5b9a\u4e49\u65c5\u6e38\u5e76\u8bc6\u522b\u4e0d\u540c\u7c7b\u578b\u7684\u65c5\u6e38\u3002" },
            { en: "I can describe positive and negative impacts of tourism on different stakeholders.", zh: "\u6211\u80fd\u63cf\u8ff0\u65c5\u6e38\u5bf9\u4e0d\u540c\u5229\u76ca\u76f8\u5173\u8005\u7684\u6b63\u9762\u548c\u8d1f\u9762\u5f71\u54cd\u3002" },
            { en: "I can explain why transport is the largest contributor to tourism\u2019s carbon footprint.", zh: "\u6211\u80fd\u89e3\u91ca\u4e3a\u4ec0\u4e48\u4ea4\u901a\u8fd0\u8f93\u662f\u65c5\u6e38\u78b3\u8db3\u8ff9\u7684\u6700\u5927\u6765\u6e90\u3002" },
          ],
        },
        {
          type: "intro",
          content: [
            { type: "text", en: "Tourism is travelling for pleasure, usually for a period of less than 6 months. It is one of the world\u2019s largest industries and takes many forms: outdoor adventure tourism, cultural or historical tourism, ecotourism, and beach tourism. Each type attracts different visitors and affects destinations in different ways.", zh: "\u65c5\u6e38\u662f\u6307\u4ee5\u4f11\u95f2\u4e3a\u76ee\u7684\u7684\u65c5\u884c\uff0c\u901a\u5e38\u6301\u7eed\u4e0d\u8d85\u8fc76\u4e2a\u6708\u3002\u65c5\u6e38\u4e1a\u662f\u5168\u7403\u6700\u5927\u7684\u4ea7\u4e1a\u4e4b\u4e00\uff0c\u5e76\u6709\u591a\u79cd\u5f62\u5f0f\uff1a\u6237\u5916\u5192\u9669\u65c5\u6e38\u3001\u6587\u5316\u6216\u5386\u53f2\u65c5\u6e38\u3001\u751f\u6001\u65c5\u6e38\u548c\u6d77\u6ee9\u65c5\u6e38\u3002\u6bcf\u79cd\u7c7b\u578b\u5438\u5f15\u4e0d\u540c\u7684\u6e38\u5ba2\uff0c\u5e76\u4ee5\u4e0d\u540c\u65b9\u5f0f\u5f71\u54cd\u76ee\u7684\u5730\u3002" },
            { type: "highlight", en: "Stakeholders in tourism and their views: Local residents \u2014 may value jobs in the tertiary sector but may dislike noise, crowding, and rising costs. Local business owners \u2014 gain customers but business can be seasonal. Tourists \u2014 enjoy the destination but too many visitors can reduce the cultural experience. Hotel chain owners \u2014 gain income but pay taxes. Local government \u2014 gains tax revenue and may use it to improve local infrastructure.", zh: "\u65c5\u6e38\u4e2d\u7684\u5229\u76ca\u76f8\u5173\u8005\u53ca\u5176\u89c2\u70b9\uff1a\u5f53\u5730\u5c45\u6c11\u2014\u2014\u53ef\u80fd\u91cd\u89c6\u7b2c\u4e09\u4ea7\u4e1a\u5c31\u4e1a\u673a\u4f1a\uff0c\u4f46\u53ef\u80fd\u4e0d\u559c\u566a\u97f3\u3001\u62e5\u6324\u548c\u7269\u4ef7\u4e0a\u6da8\u3002\u5f53\u5730\u4e1a\u4e3b\u2014\u2014\u83b7\u5f97\u5ba2\u6237\uff0c\u4f46\u751f\u610f\u53ef\u80fd\u5177\u6709\u5b63\u8282\u6027\u3002\u6e38\u5ba2\u2014\u2014\u4eab\u53d7\u76ee\u7684\u5730\uff0c\u4f46\u6e38\u5ba2\u8fc7\u591a\u4f1a\u964d\u4f4e\u6587\u5316\u4f53\u9a8c\u3002\u9152\u5e97\u8fde\u9501\u8001\u677f\u2014\u2014\u83b7\u5f97\u6536\u5165\u4f46\u9700\u7eb3\u7a0e\u3002\u5730\u65b9\u653f\u5e9c\u2014\u2014\u83b7\u5f97\u7a0e\u6536\u5e76\u53ef\u7528\u4e8e\u6539\u5584\u5f53\u5730\u57fa\u7840\u8bbe\u65bd\u3002" },
            { type: "text", en: "Tourism also has an environmental impact. Transport contributes the largest share of tourism\u2019s carbon footprint at 49%. This means that flights, cruise ships, and long road journeys to tourist destinations produce nearly half of all the greenhouse gas emissions generated by the tourism industry. This is an important reason why sustainable tourism is increasingly discussed.", zh: "\u65c5\u6e38\u8fd8\u5177\u6709\u73af\u5883\u5f71\u54cd\u3002\u4ea4\u901a\u8fd0\u8f93\u5360\u65c5\u6e38\u78b3\u8db3\u8ff9\u7684\u6700\u5927\u6bd4\u4f8b\uff0c\u9ad849%\u3002\u8fd9\u610f\u5473\u7740\uff0c\u5de5\u9ad8\u3001\u6e38\u8f6e\u548c\u524d\u5f80\u65c5\u6e38\u76ee\u7684\u5730\u7684\u957f\u9014\u516c\u8def\u4e4b\u65c5\u4ea7\u751f\u7684\u6e29\u5ba4\u6c14\u4f53\u6392\u653e\u91cf\uff0c\u5360\u65c5\u6e38\u4e1a\u603b\u6392\u653e\u91cf\u7684\u8fd145%\u3002\u8fd9\u662f\u53ef\u6301\u7eed\u65c5\u6e38\u8d8a\u6765\u8d8a\u53d7\u5230\u5173\u6ce8\u7684\u91cd\u8981\u539f\u56e0\u3002" },
          ],
        },
        {
          type: "vocab",
          words: [
            { en: "Tourism", zh: "\u65c5\u6e38", defEn: "Travelling for pleasure, usually for a period of less than 6 months.", defZh: "\u4ee5\u4f11\u95f2\u4e3a\u76ee\u7684\u7684\u65c5\u884c\uff0c\u901a\u5e38\u6301\u7eed\u4e0d\u8d85\u8fc76\u4e2a\u6708\u3002" },
            { en: "Stakeholder", zh: "\u5229\u76ca\u76f8\u5173\u8005", defEn: "A person or group that has an interest in or is affected by a decision or activity.", defZh: "\u5bf9\u67d0\u4e00\u51b3\u7b56\u6216\u6d3b\u52a8\u6709\u5229\u76ca\u5173\u7cfb\u6216\u53d7\u5176\u5f71\u54cd\u7684\u4e2a\u4eba\u6216\u7fa4\u4f53\u3002" },
            { en: "Carbon footprint", zh: "\u78b3\u8db3\u8ff9", defEn: "The total amount of greenhouse gases produced by an activity, measured in carbon dioxide equivalent.", defZh: "\u4e00\u9879\u6d3b\u52a8\u4ea7\u751f\u7684\u6e29\u5ba4\u6c14\u4f53\u603b\u91cf\uff0c\u4ee5\u4e8c\u6c27\u5316\u78b3\u5f53\u91cf\u8861\u91cf\u3002" },
            { en: "Ecotourism", zh: "\u751f\u6001\u65c5\u6e38", defEn: "Tourism directed towards natural environments that aims to support conservation and benefit local communities.", defZh: "\u9488\u5bf9\u81ea\u7136\u73af\u5883\u3001\u65e8\u5728\u652f\u6301\u4fdd\u62a4\u5e76\u60e0\u53ca\u5f53\u5730\u793e\u533a\u7684\u65c5\u6e38\u3002" },
          ],
        },
        { type: "image", caption: "A diagram showing the carbon footprint of tourism by sector, with transport at 49%.", captionZh: "\u65c5\u6e38\u4e1a\u5404\u9886\u57df\u78b3\u8db3\u8ff9\u793a\u610f\u56fe\uff0c\u4ea4\u901a\u8fd0\u8f93\u536049%\u3002", source: "Placeholder \u2014 image to be added" },
        { type: "source", labelEn: "Key Statistic: Tourism Carbon Footprint", labelZh: "\u5173\u952e\u6570\u636e\uff1a\u65c5\u6e38\u78b3\u8db3\u8ff9", en: "Transport contributes 49% of tourism\u2019s carbon footprint. This includes flights, cruise ships, and road travel to destinations. Tourism is defined as travelling for pleasure, usually for less than 6 months.", zh: "\u4ea4\u901a\u8fd0\u8f93\u5360\u65c5\u6e38\u78b3\u8db3\u8ff9\u7684 49%\uff0c\u5305\u62ec\u6307\u5f80\u76ee\u7684\u5730\u7684\u6c99\u7ebf\u3001\u6e38\u8f6e\u548c\u516c\u8def\u65c5\u884c\u3002\u65c5\u6e38\u5b9a\u4e49\u4e3a\u4ee5\u4f11\u95f2\u4e3a\u76ee\u7684\u7684\u65c5\u884c\uff0c\u901a\u5e38\u6301\u7eed\u4e0d\u8d85\u8fc76\u4e2a\u6708\u3002" },
        {
          type: "think",
          questions: [
            { qEn: "Give one positive and one negative impact of tourism on local residents.", qZh: "\u5404\u4e3e\u4e00\u4e2a\u65c5\u6e38\u5bf9\u5f53\u5730\u5c45\u6c11\u7684\u6b63\u9762\u5f71\u54cd\u548c\u8d1f\u9762\u5f71\u54cd\u3002", aEn: "Positive: tourism creates jobs in the tertiary sector such as hotels, restaurants, and transport, giving local people a source of income. Negative: large numbers of tourists can cause overcrowding, noise, and rising prices for goods and housing, which reduce the quality of life for residents.", aZh: "\u6b63\u9762\uff1a\u65c5\u6e38\u5728\u7b2c\u4e09\u4ea7\u4e1a\uff08\u5982\u9152\u5e97\u3001\u9910\u5385\u548c\u4ea4\u901a\uff09\u521b\u9020\u5c31\u4e1a\u673a\u4f1a\uff0c\u4e3a\u5f53\u5730\u4eba\u63d0\u4f9b\u6536\u5165\u6765\u6e90\u3002\u8d1f\u9762\uff1a\u5927\u91cf\u6e38\u5ba2\u53ef\u80fd\u5bfc\u81f4\u62e5\u6324\u3001\u566a\u97f3\u4ee5\u53ca\u5546\u54c1\u548c\u623f\u5c4b\u4ef7\u683c\u4e0a\u6da8\uff0c\u964d\u4f4e\u5c45\u6c11\u7684\u751f\u6d3b\u8d28\u91cf\u3002" },
            { qEn: "Why is transport responsible for such a large share of tourism\u2019s carbon footprint?", qZh: "\u4e3a\u4ec0\u4e48\u4ea4\u901a\u8fd0\u8f93\u5360\u65c5\u6e38\u78b3\u8db3\u8ff9\u5982\u6b64\u5927\u7684\u6bd4\u4f8b\uff1f", aEn: "Getting to a tourist destination usually requires long-distance travel by plane, ship, or car. Aeroplanes in particular burn large amounts of fuel and produce significant CO2 emissions over long distances. Since travel is a fundamental part of tourism, it is unavoidable unless tourists choose closer or lower-carbon destinations.", aZh: "\u524d\u5f80\u65c5\u6e38\u76ee\u7684\u5730\u901a\u5e38\u9700\u8981\u4e58\u98de\u673a\u3001\u8f6e\u8239\u6216\u6c7d\u8f66\u8fdb\u884c\u957f\u9014\u65c5\u884c\u3002\u5c24\u5176\u662f\u98de\u673a\uff0c\u5728\u957f\u9014\u98de\u884c\u4e2d\u6d88\u8017\u5927\u91cf\u71c3\u6599\u5e76\u4ea7\u751f\u5927\u91cf\u4e8c\u6c27\u5316\u78b3\u6392\u653e\u3002\u7531\u4e8e\u65c5\u884c\u662f\u65c5\u6e38\u7684\u57fa\u672c\u7ec4\u6210\u90e8\u5206\uff0c\u8fd9\u662f\u96be\u4ee5\u907f\u514d\u7684\uff0c\u9664\u975e\u6e38\u5ba2\u9009\u62e9\u66f4\u8fd1\u6216\u78b3\u6392\u653e\u66f4\u4f4e\u7684\u76ee\u7684\u5730\u3002" },
          ],
        },
        {
          type: "quiz",
          qEn: "What percentage of tourism\u2019s carbon footprint does transport contribute?",
          qZh: "\u4ea4\u901a\u8fd0\u8f93\u5360\u65c5\u6e38\u78b3\u8db3\u8ff9\u7684\u767e\u5206\u4e4b\u51e0\uff1f",
          opts: [
            { en: "19%", zh: "19%" },
            { en: "29%", zh: "29%" },
            { en: "49%", zh: "49%" },
            { en: "69%", zh: "69%" },
          ],
          correct: 2,
          explainCorrectEn: "Correct! Transport contributes 49% of tourism\u2019s carbon footprint \u2014 the largest single share \u2014 mainly due to flights and cruise ships.",
          explainCorrectZh: "\u6b63\u786e\uff01\u4ea4\u901a\u8fd0\u8f93\u5360\u65c5\u6e38\u78b3\u8db3\u8ff9\u768449%\u2014\u2014\u662f\u6700\u5927\u7684\u5355\u4e00\u6765\u6e90\u2014\u2014\u4e3b\u8981\u6765\u81ea\u6c99\u7ebf\u548c\u6e38\u8f6e\u3002",
          explainWrongEn: "Not quite. Transport accounts for 49% \u2014 the single largest contributor to tourism\u2019s carbon footprint. The correct answer is 49%.",
          explainWrongZh: "\u4e0d\u5bf9\u3002\u4ea4\u901a\u8fd0\u8f93\u5360 49%\u2014\u2014\u662f\u65c5\u6e38\u78b3\u8db3\u8ff9\u6700\u5927\u7684\u5355\u4e00\u6765\u6e90\u3002\u6b63\u786e\u7b54\u6848\u662f 49%\u3002",
        },
      ],
    },

    /* ========== Lesson 2 ========== */
    {
      num: 2,
      badge: "T",
      title: "The growth of tourism",
      titleZh: "\u65c5\u6e38\u4e1a\u7684\u589e\u957f",
      subtitle: "International tourism has grown dramatically \u2014 but not everywhere equally, and not without interruption.",
      subtitleZh: "\u56fd\u9645\u65c5\u6e38\u4e1a\u5927\u5e45\u589e\u957f\u2014\u2014\u4f46\u5e76\u975e\u5404\u5730\u5747\u7b49\uff0c\u4e5f\u5e76\u975e\u4e0d\u65ad\u3002",
      sections: [
        {
          type: "goals",
          items: [
            { en: "I can describe the trend in international tourist arrivals to Thailand using the TEA method.", zh: "\u6211\u80fd\u8fd0\u7528TEA\u6cd5\u63cf\u8ff0\u56fd\u9645\u6e38\u5ba2\u5230\u6cf0\u56fd\u7684\u5165\u5883\u8d8b\u52bf\u3002" },
            { en: "I can explain why 2020 was an anomaly in tourism data.", zh: "\u6211\u80fd\u89e3\u91ca\u4e3a\u4ec0\u4e482020\u5e74\u662f\u65c5\u6e38\u6570\u636e\u4e2d\u7684\u5f02\u5e38\u5e74\u3002" },
            { en: "I can identify reasons why international tourism has grown.", zh: "\u6211\u80fd\u8bc6\u522b\u56fd\u9645\u65c5\u6e38\u589e\u957f\u7684\u539f\u56e0\u3002" },
          ],
        },
        {
          type: "intro",
          content: [
            { type: "text", en: "International tourist arrivals to Thailand grew strongly from 2015 onwards, before collapsing dramatically in 2020. In 2016, Thailand received 32.85 million international tourist arrivals \u2014 the second highest in Asia after China (59.27 million). By contrast, Nepal received 0.75 million and Bhutan just 0.21 million, showing how unequally tourism is distributed across Asia.", zh: "\u56fd\u9645\u6e38\u5ba2\u5165\u5883\u6cf0\u56fd\u7684\u4eba\u6570\u81ea2015\u5e74\u5f00\u59cb\u5927\u5e45\u589e\u957f\uff0c\u76f42020\u5e74\u624d\u6025\u5267\u5d29\u6e83\u30022016\u5e74\uff0c\u6cf0\u56fd\u5171\u63a53285\u4e07\u56fd\u9645\u6e38\u5ba2\uff0c\u4ec85927\u4e07\u7684\u4e2d\u56fd\u540e\u5c45\u4e9a\u6d32\u7b2c\u4e8c\u3002\u76f8\u6bd4\u4e4b\u4e0b\uff0c\u5c3c\u6cca\u5c14\u4ec85\u4e07\u4eba\u3001\u4e0d\u4e39\u4ec1\u4ec52.1\u4e07\u4eba\uff0c\u53ef\u89c1\u65c5\u6e38\u4e1a\u5728\u4e9a\u6d32\u5404\u5730\u5206\u5e03\u6781\u4e0d\u5747\u5747\u3002" },
            { type: "highlight", en: "Reasons why tourism has grown: people are wealthier and have more disposable income; more families have two working parents, meaning they can afford holidays; people have fewer children; car ownership has grown; people live longer and travel in retirement; flights have become cheaper; online booking is quick and easy. All these factors have made tourism more accessible to more people.", zh: "\u65c5\u6e38\u589e\u957f\u7684\u539f\u56e0\uff1a\u4eba\u4eec\u8d8a\u6765\u8d8a\u5bcc\u88d5\uff0c\u53ef\u652f\u914d\u6536\u5165\u589e\u52a0\uff1b\u66f4\u591a\u5bb6\u5ead\u53cc\u65b9\u90fd\u5de5\u4f5c\uff0c\u610f\u5473\u7740\u6709\u80fd\u529b\u5ea6\u5047\uff1b\u5bb6\u5ead\u5b50\u5973\u6570\u91cf\u51cf\u5c11\uff1b\u6c7d\u8f66\u62e5\u6709\u91cf\u589e\u52a0\uff1b\u4eba\u4e1a\u5bff\u547d\u5ef6\u957f\uff0c\u9000\u4f11\u540e\u65c5\u884c\uff1b\u673a\u7968\u4ef7\u683c\u964d\u4f4e\uff1b\u7f51\u7edc\u9884\u8ba2\u5feb\u6377\u65b9\u4fbf\u3002\u8fd9\u4e9b\u56e0\u7d20\u90fd\u4f7f\u65c5\u6e38\u5bf9\u66f4\u591a\u4eba\u66f4\u52a0\u53ef\u5b9e\u73b0\u3002" },
            { type: "example", en: "Applying the TEA method to Thailand\u2019s tourism data: Trend \u2014 international tourist arrivals to Thailand grew consistently from 2015. Evidence \u2014 Thailand received 32.85 million arrivals in 2016. Anomaly \u2014 2020 saw a dramatic collapse in arrivals because of the COVID-19 pandemic, which closed borders and halted international travel worldwide. This is a clear anomaly because it does not fit the strong upward trend.", zh: "\u5c06TEA\u6cd5\u5e94\u7528\u4e8e\u6cf0\u56fd\u65c5\u6e38\u6570\u636e\uff1a\u8d8b\u52bf\u2014\u2014\u56fd\u9645\u6e38\u5ba2\u5165\u5883\u6cf0\u56fd\u4eba\u65702015\u5e74\u5f00\u59cb\u6301\u7eed\u589e\u957f\u3002\u8bc1\u636e\u2014\u20142016\u5e74\u6cf0\u56fd\u63a53285\u4e07\u5165\u5883\u6e38\u5ba2\u3002\u5f02\u5e38\u503c\u2014\u20142020\u5e74\u65c5\u6e38\u4eba\u6570\u6025\u5267\u5d29\u6e83\uff0c\u539f\u56e0\u662f\u65b0\u51a0\u75ab\u60c5\u5bfc\u81f4\u8fb9\u5883\u5c01\u9501\u548c\u5168\u7403\u56fd\u9645\u65c5\u884c\u6682\u505c\u3002\u8fd9\u662f\u4e00\u4e2a\u660e\u663e\u7684\u5f02\u5e38\u503c\uff0c\u56e0\u4e3a\u5b83\u4e0d\u7b26\u5408\u5f3a\u52b2\u7684\u4e0a\u5347\u8d8b\u52bf\u3002" },
          ],
        },
        {
          type: "vocab",
          words: [
            { en: "International tourist arrivals", zh: "\u56fd\u9645\u6e38\u5ba2\u5165\u5883\u4eba\u6570", defEn: "The number of visitors from other countries who arrive in a destination country.", defZh: "\u5230\u8fbe\u76ee\u7684\u56fd\u5bb6\u7684\u5916\u56fd\u6e38\u5ba2\u4eba\u6570\u3002" },
            { en: "Disposable income", zh: "\u53ef\u652f\u914d\u6536\u5165", defEn: "The money a person has left to spend after paying taxes and essential bills.", defZh: "\u4e00\u4e2a\u4eba\u7f34\u5b8c\u7a0e\u6b3e\u548c\u5fc5\u8981\u8d39\u7528\u540e\u5269\u4f59\u53ef\u652f\u914d\u7684\u8d44\u91d1\u3002" },
            { en: "Tourist arrivals data", zh: "\u6e38\u5ba2\u5165\u5883\u6570\u636e", defEn: "Statistical records showing how many tourists visited a country or region in a given period.", defZh: "\u663e\u793a\u4e00\u5b9a\u65f6\u671f\u5185\u5230\u8bbf\u4e00\u4e2a\u56fd\u5bb6\u6216\u5730\u533a\u6e38\u5ba2\u4eba\u6570\u7684\u7edf\u8ba1\u8bb0\u5f55\u3002" },
            { en: "Anomaly", zh: "\u5f02\u5e38\u503c", defEn: "A data point or event that does not fit the general trend.", defZh: "\u4e0d\u7b26\u5408\u603b\u4f53\u8d8b\u52bf\u7684\u6570\u636e\u70b9\u6216\u4e8b\u4ef6\u3002" },
          ],
        },
        { type: "image", caption: "A graph showing international tourist arrivals to Thailand from 2015, with the 2020 anomaly.", captionZh: "\u56fe\u8868\u5c55\u793a2015\u5e74\u4ee5\u6765\u56fd\u9645\u6e38\u5ba2\u5165\u5883\u6cf0\u56fd\u7684\u4eba\u6570\uff0c\u5305\u62ec2020\u5e74\u7684\u5f02\u5e38\u503c\u3002", source: "Placeholder \u2014 image to be added" },
        { type: "source", labelEn: "Tourist Arrivals Data: Asia 2016", labelZh: "\u6e38\u5ba2\u5165\u5883\u6570\u636e\uff1a\u4e9a\u6d322016\u5e74", en: "In 2016, China received 59.27 million international tourist arrivals; Thailand 32.85 million; Malaysia 26.75 million; Japan 24.03 million. By contrast, Nepal received 0.75 million and Bhutan 0.21 million. Tourism is very unevenly distributed across Asia.", zh: "2016\u5e74\uff0c\u4e2d\u56fd\u5171\u63a55927\u4e07\u56fd\u9645\u6e38\u5ba2\uff1b\u6cf0\u56fd3285\u4e07\uff1b\u9a6c\u6765\u897f\u4e9a2675\u4e07\uff1b\u65e5\u672c2403\u4e07\u3002\u76f8\u6bd4\u4e4b\u4e0b\uff0c\u5c3c\u6cca\u5c1475\u4e07\uff0c\u4e0d\u4e3921\u4e07\u3002\u65c5\u6e38\u4e1a\u5728\u4e9a\u6d32\u5404\u5730\u5206\u5e03\u6781\u4e0d\u5747\u5747\u3002" },
        {
          type: "think",
          questions: [
            { qEn: "Give three reasons why international tourism has grown over recent decades.", qZh: "\u5217\u51fa\u8fd1\u51e0\u5341\u5e74\u6765\u56fd\u9645\u65c5\u6e38\u589e\u957f\u7684\u4e09\u4e2a\u539f\u56e0\u3002", aEn: "First, people have more disposable income as wages have risen, allowing them to afford holidays. Second, flights have become much cheaper due to budget airlines, making long-distance travel accessible to more people. Third, online booking platforms have made it quick and easy to compare prices and arrange travel, reducing barriers to booking a trip.", aZh: "\u7b2c\u4e00\uff0c\u968f\u7740\u5de5\u8d44\u4e0a\u6da8\uff0c\u4eba\u4eec\u53ef\u652f\u914d\u6536\u5165\u589e\u52a0\uff0c\u6709\u80fd\u529b\u8d1f\u62c5\u5ea6\u5047\u5f00\u9500\u3002\u7b2c\u4e8c\uff0c\u4f4e\u6210\u672c\u822a\u7a7a\u516c\u53f8\u4f7f\u673a\u7968\u4ef7\u683c\u5927\u5e45\u4e0b\u964d\uff0c\u8ba9\u66f4\u591a\u4eba\u53ef\u4ee5\u8fdb\u884c\u8fdc\u7a0b\u65c5\u884c\u3002\u7b2c\u4e09\uff0c\u7f51\u7edc\u9884\u8ba2\u5e73\u53f0\u4f7f\u6bd4\u4ef7\u548c\u5b89\u6392\u65c5\u884c\u53d8\u5f97\u5feb\u6377\u65b9\u4fbf\uff0c\u964d\u4f4e\u4e86\u9884\u8ba2\u7684\u95e8\u69db\u3002" },
            { qEn: "Why was 2020 an anomaly in Thailand\u2019s tourism data? What caused it?", qZh: "\u4e3a\u4ec0\u4e482020\u5e74\u662f\u6cf0\u56fd\u65c5\u6e38\u6570\u636e\u4e2d\u7684\u5f02\u5e38\u5e74\uff1f\u662f\u4ec0\u4e48\u5bfc\u81f4\u7684\uff1f", aEn: "2020 was an anomaly because international tourist arrivals collapsed dramatically, breaking the strong upward trend that had built up since 2015. The cause was the COVID-19 pandemic, which led governments around the world to close their borders and halt international travel to prevent the spread of the virus.", aZh: "2020\u5e74\u662f\u5f02\u5e38\u5e74\uff0c\u56e0\u4e3a\u56fd\u9645\u6e38\u5ba2\u5165\u5883\u4eba\u6570\u6025\u5267\u5d29\u6e83\uff0c\u6253\u7834\u4e862015\u5e74\u4ee5\u6765\u5efa\u7acb\u7684\u5f3a\u52b2\u4e0a\u5347\u8d8b\u52bf\u3002\u539f\u56e0\u662f\u65b0\u51a0\u75ab\u60c5\uff0c\u5bfc\u81f4\u5168\u7403\u5404\u56fd\u653f\u5e9c\u5c01\u9501\u8fb9\u5883\u5e76\u6682\u505c\u56fd\u9645\u65c5\u884c\uff0c\u4ee5\u9632\u6b62\u75c5\u6bc2\u4f20\u64ad\u3002" },
          ],
        },
        {
          type: "quiz",
          qEn: "How many international tourist arrivals did Thailand receive in 2016?",
          qZh: "2016\u5e74\u6cf0\u56fd\u63a5\u5f85\u4e86\u591a\u5c11\u56fd\u9645\u6e38\u5ba2\uff1f",
          opts: [
            { en: "59.27 million", zh: "5927\u4e07" },
            { en: "32.85 million", zh: "3285\u4e07" },
            { en: "26.75 million", zh: "2675\u4e07" },
            { en: "24.03 million", zh: "2403\u4e07" },
          ],
          correct: 1,
          explainCorrectEn: "Correct! Thailand received 32.85 million international tourist arrivals in 2016 \u2014 the second highest in Asia after China\u2019s 59.27 million.",
          explainCorrectZh: "\u6b63\u786e\uff01\u6cf0\u56fd2016\u5e74\u63a53285\u4e07\u56fd\u9645\u6e38\u5ba2\uff0c\u4ec5\u6b21\u4e8e\u4e2d\u56fd\u76845927\u4e07\uff0c\u5c45\u4e9a\u6d32\u7b2c\u4e8c\u3002",
          explainWrongEn: "Not quite. 59.27 million was China; 26.75 million was Malaysia; 24.03 million was Japan. Thailand received 32.85 million in 2016.",
          explainWrongZh: "\u4e0d\u5bf9\u30025927\u4e07\u662f\u4e2d\u56fd\uff0c2675\u4e07\u662f\u9a6c\u6765\u897f\u4e9a\uff0c2403\u4e07\u662f\u65e5\u672c\u3002\u6cf0\u56fd2016\u5e74\u63a53285\u4e07\u6e38\u5ba2\u3002",
        },
      ],
    },

    /* ========== Lesson 3 ========== */
    {
      num: 3,
      badge: "T",
      title: "Mass tourism and Koh Phi Phi",
      titleZh: "\u5927\u4f17\u65c5\u6e38\u4e0e\u8482\u8482\u5c9b",
      subtitle: "When tourism grows too fast without management, destinations become overrun \u2014 and social media is making this problem worse.",
      subtitleZh: "\u65c5\u6e38\u5728\u7f3a\u4e4f\u7ba1\u7406\u7684\u60c5\u51b5\u4e0b\u5feb\u901f\u589e\u957f\uff0c\u76ee\u7684\u5730\u5c31\u4f1a\u88ab\u6e38\u5ba2\u6df9\u6ca1\u2014\u2014\u793e\u4ea4\u5a92\u4f53\u6b63\u5728\u52a0\u5265\u8fd9\u4e00\u95ee\u9898\u3002",
      sections: [
        {
          type: "goals",
          items: [
            { en: "I can define mass tourism and explain how it differs from sustainable tourism.", zh: "\u6211\u80fd\u5b9a\u4e49\u5927\u4f17\u65c5\u6e38\uff0c\u5e76\u89e3\u91ca\u5b83\u4e0e\u53ef\u6301\u7eed\u65c5\u6e38\u7684\u533a\u522b\u3002" },
            { en: "I can explain how social media contributes to overtourism.", zh: "\u6211\u80fd\u89e3\u91ca\u793e\u4ea4\u5a92\u4f53\u5982\u4f55\u52a0\u5267\u8fc7\u5ea6\u65c5\u6e38\u3002" },
            { en: "I can describe the location of Koh Phi Phi and explain why Maya Bay became a victim of overtourism.", zh: "\u6211\u80fd\u63cf\u8ff0\u8482\u8482\u5c9b\u7684\u5730\u7406\u4f4d\u7f6e\uff0c\u5e76\u89e3\u91ca\u739b\u96c5\u6e7e\u4e3a\u4ec0\u4e48\u6210\u4e3a\u8fc7\u5ea6\u65c5\u6e38\u7684\u53d7\u5bb3\u8005\u3002" },
          ],
        },
        {
          type: "intro",
          content: [
            { type: "text", en: "Mass tourism occurs when a popular destination becomes overrun with tourists in an unsustainable way. Sustainability means meeting present needs without harming the ability of future generations to meet their own needs. When visitor numbers exceed what a destination can manage, the result is overtourism: environmental damage, loss of local culture, and reduced quality of experience for everyone.", zh: "\u5927\u4f17\u65c5\u6e38\u662f\u6307\u4e00\u4e2a\u53d7\u6b22\u8fce\u7684\u76ee\u7684\u5730\u4ee5\u4e0d\u53ef\u6301\u7eed\u7684\u65b9\u5f0f\u88ab\u6e38\u5ba2\u6df9\u6ca1\u3002\u53ef\u6301\u7eed\u6027\u662f\u6307\u5728\u4e0d\u635f\u5bb3\u540e\u4ee3\u6ee1\u8db3\u5176\u81ea\u8eab\u9700\u6c42\u7684\u80fd\u529b\u7684\u524d\u63d0\u4e0b\u6ee1\u8db3\u5f53\u524d\u9700\u6c42\u3002\u5f53\u6e38\u5ba2\u6570\u91cf\u8d85\u8fc7\u76ee\u7684\u5730\u7684\u627f\u5bb9\u80fd\u529b\u65f6\uff0c\u5c31\u4f1a\u51fa\u73b0\u8fc7\u5ea6\u65c5\u6e38\uff1a\u73af\u5883\u7834\u574f\u3001\u5f53\u5730\u6587\u5316\u4e27\u5931\u548c\u6e38\u5ba2\u4f53\u9a8c\u8d28\u91cf\u4e0b\u964d\u3002" },
            { type: "highlight", en: "How social media drives overtourism: people research destinations online and are influenced by posts, reviews, and photos on platforms like Instagram and TripAdvisor. When a location goes viral, it can attract far more visitors than it can sustainably handle. Social media made Koh Phi Phi and Maya Bay globally famous, contributing to the overcrowding that eventually forced the closure of Maya Bay.", zh: "\u793e\u4ea4\u5a92\u4f53\u5982\u4f55\u63a8\u52a8\u8fc7\u5ea6\u65c5\u6e38\uff1a\u4eba\u4eec\u5728\u7f51\u4e0a\u7814\u7a76\u65c5\u6e38\u76ee\u7684\u5730\uff0c\u5e76\u53d7\u5230Instagram\u548cTripAdvisor\u7b49\u5e73\u53f0\u4e0a\u5e16\u5b50\u3001\u8bc4\u8bba\u548c\u7167\u7247\u7684\u5f71\u54cd\u3002\u5f53\u67d0\u4e2a\u5730\u70b9\u5728\u7f51\u4e0a\u71ac\u706b\u65f6\uff0c\u5438\u5f15\u7684\u6e38\u5ba2\u5f80\u5f80\u8fdc\u8d85\u8fc7\u5176\u53ef\u6301\u7eed\u627f\u638e\u7684\u6570\u91cf\u3002\u793e\u4ea4\u5a92\u4f53\u8ba9\u8482\u8482\u5c9b\u548c\u739b\u96c5\u6e7e\u95fb\u540d\u5168\u7403\uff0c\u52a0\u5267\u4e86\u62e5\u6324\u95ee\u9898\uff0c\u6700\u7ec8\u8feb\u4f7f\u739b\u96c5\u6e7e\u5173\u95ed\u3002" },
            { type: "text", en: "Koh Phi Phi is a group of islands in Thailand, east of Phuket, in Krabi province, about 800 km south-west of Bangkok. Maya Bay on Koh Phi Phi became especially famous after the film \u2018The Beach\u2019 was filmed there in 1999. Visitor numbers grew rapidly and the bay suffered severe environmental damage: coral reefs were destroyed by boat anchors, plastic waste accumulated, and the ecosystem was placed under extreme stress.", zh: "\u8482\u8482\u5c9b\u662f\u6cf0\u56fd\u7684\u4e00\u7ec4\u5c9b\u5c7f\uff0c\u4f4d\u4e8e\u666e\u5409\u4e1c\u7684\u514b\u62c9\u6bd4\u5e9c\uff0c\u79bb\u66f2\u8c37\u897f\u5357\u51688\u767e\u516c\u91cc\u5de6\u53f3\u3002\u8482\u8482\u5c9b\u4e0a\u7684\u739b\u96c5\u6e7e\u56e01999\u5e74\u62cd\u6444\u7535\u5f71\u300a\u6d77\u6ee9\u300b\u800c\u95fb\u540d\u5929\u4e0b\u3002\u6e38\u5ba2\u4eba\u6570\u8fc5\u901f\u589e\u52a0\uff0c\u6e7e\u533a\u9047\u5230\u4e25\u91cd\u73af\u5883\u7834\u574f\uff1a\u73ca\u745a\u793c\u7901\u88ab\u8239\u9524\u6bc1\uff0c\u5851\u6599\u5783\u573e\u5806\u79ef\uff0c\u751f\u6001\u7cfb\u7edf\u627f\u53d7\u6781\u5927\u538b\u529b\u3002" },
          ],
        },
        {
          type: "vocab",
          words: [
            { en: "Mass tourism", zh: "\u5927\u4f17\u65c5\u6e38", defEn: "When a popular destination becomes overrun with tourists in an unsustainable way.", defZh: "\u4e00\u4e2a\u53d7\u6b22\u8fce\u7684\u76ee\u7684\u5730\u4ee5\u4e0d\u53ef\u6301\u7eed\u7684\u65b9\u5f0f\u88ab\u6e38\u5ba2\u6df9\u6ca1\u3002" },
            { en: "Overtourism", zh: "\u8fc7\u5ea6\u65c5\u6e38", defEn: "When visitor numbers exceed what a destination can sustainably manage, causing environmental and social problems.", defZh: "\u5f53\u6e38\u5ba2\u6570\u91cf\u8d85\u8fc7\u76ee\u7684\u5730\u53ef\u6301\u7eed\u627f\u8f7d\u7684\u8303\u56f4\uff0c\u5bfc\u81f4\u73af\u5883\u548c\u793e\u4f1a\u95ee\u9898\u3002" },
            { en: "Sustainability", zh: "\u53ef\u6301\u7eed\u6027", defEn: "Meeting present needs without harming the ability of future generations to meet their own needs.", defZh: "\u5728\u4e0d\u635f\u5bb3\u540e\u4ee3\u6ee1\u8db3\u5176\u81ea\u8eab\u9700\u6c42\u7684\u80fd\u529b\u7684\u524d\u63d0\u4e0b\uff0c\u6ee1\u8db3\u5f53\u4e0b\u9700\u6c42\u3002" },
            { en: "Coral reef", zh: "\u73ca\u745a\u793c\u7901", defEn: "An underwater ecosystem built by coral polyps, highly sensitive to pollution and physical damage.", defZh: "\u7531\u73ca\u745a\u866b\u6784\u5efa\u7684\u6c34\u4e0b\u751f\u6001\u7cfb\u7edf\uff0c\u5bf9\u6c61\u67d3\u548c\u7269\u7406\u635f\u574f\u9ad8\u5ea6\u654f\u611f\u3002" },
          ],
        },
        { type: "image", caption: "Koh Phi Phi and Maya Bay, Thailand \u2014 a destination made famous by the 1999 film \u2018The Beach\u2019.", captionZh: "\u6cf0\u56fd\u8482\u8482\u5c9b\u4e0e\u739b\u96c5\u6e7e\u2014\u2014\u56e01999\u5e74\u7535\u5f71\u300a\u6d77\u6ee9\u300b\u800c\u95fb\u540d\u5929\u4e0b\u7684\u65c5\u6e38\u76ee\u7684\u5730\u3002", source: "Placeholder \u2014 image to be added" },
        { type: "source", labelEn: "Case Study: Maya Bay, Koh Phi Phi", labelZh: "\u6848\u4f8b\u7814\u7a76\uff1a\u8482\u8482\u5c9b\u739b\u96c5\u6e7e", en: "Koh Phi Phi is in Krabi province, Thailand, about 800 km south-west of Bangkok. Maya Bay became famous after the film \u2018The Beach\u2019 (1999). Rapid tourist growth caused coral reef destruction, plastic pollution, and ecosystem damage, eventually leading to the bay\u2019s closure in June 2018.", zh: "\u8482\u8482\u5c9b\u4f4d\u4e8e\u6cf0\u56fd\u514b\u62c9\u6bd4\u5e9c\uff0c\u79bb\u66f2\u8c37\u897f\u5357\u51688\u767e\u516c\u91cc\u3002\u739b\u96c5\u6e7e\u56e0\u300a\u6d77\u6ee9\u300b\uff081999\u5e74\uff09\u800c\u95fb\u540d\u3002\u65c5\u6e38\u8fc5\u901f\u589e\u957f\u5bfc\u81f4\u73ca\u745a\u793c\u7901\u88ab\u6bc1\u3001\u5851\u6599\u6c61\u67d3\u548c\u751f\u6001\u7cfb\u7edf\u7834\u574f\uff0c\u6700\u7ec82018\u5e746\u6708\u88ab\u8feb\u5173\u95ed\u3002" },
        {
          type: "think",
          questions: [
            { qEn: "Explain how social media can contribute to overtourism at a destination like Maya Bay.", qZh: "\u89e3\u91ca\u793e\u4ea4\u5a92\u4f53\u5982\u4f55\u5bfc\u81f4\u739b\u96c5\u6e7e\u8fd9\u6837\u7684\u76ee\u7684\u5730\u51fa\u73b0\u8fc7\u5ea6\u65c5\u6e38\u3002", aEn: "Social media platforms such as Instagram allow users to share photos of beautiful or unusual destinations. When images of Maya Bay spread online, they attracted huge numbers of visitors who wanted to experience the same location. Reviews on sites like TripAdvisor reinforced interest. The result was far more visitors than the fragile bay ecosystem could handle.", aZh: "Instagram\u7b49\u793e\u4ea4\u5a92\u4f53\u5e73\u53f0\u5141\u8bb8\u7528\u6237\u5206\u4eab\u7f8e\u4e3d\u6216\u72ec\u7279\u5730\u70b9\u7684\u7167\u7247\u3002\u5f53\u739b\u96c5\u6e7e\u7684\u56fe\u7247\u5728\u7f51\u4e0a\u4f20\u64ad\u5f00\u6765\uff0c\u5438\u5f15\u4e86\u5927\u91cf\u5e0c\u671b\u4eb2\u8eab\u4f53\u9a8c\u540c\u4e00\u5730\u70b9\u7684\u6e38\u5ba2\u3002TripAdvisor\u7b49\u7f51\u7ad9\u7684\u8bc4\u8bba\u8fdb\u4e00\u6b65\u5f3a\u5316\u4e86\u5174\u8da3\u3002\u7ed3\u679c\u662f\u8fd9\u4e2a\u8106\u5f31\u7684\u6e7e\u533a\u751f\u6001\u7cfb\u7edf\u6240\u80fd\u627f\u8f7d\u7684\u6e38\u5ba2\u8fdc\u8fdc\u8d85\u8fc7\u5176\u627f\u8f7d\u80fd\u529b\u3002" },
            { qEn: "Describe the environmental damage caused by mass tourism at Maya Bay.", qZh: "\u63cf\u8ff0\u5927\u4f17\u65c5\u6e38\u5bf9\u739b\u96c5\u6e7e\u9020\u6210\u7684\u73af\u5883\u7834\u574f\u3002", aEn: "Mass tourism at Maya Bay caused coral reef destruction when boat anchors physically broke apart the reefs. Plastic waste from tourist boats and visitors accumulated in the water and on the beach. The large number of boats in the bay disturbed marine ecosystems. Overall, the natural environment that made Maya Bay attractive was being severely degraded by the same tourism it attracted.", aZh: "\u5927\u4f17\u65c5\u6e38\u5bf9\u739b\u96c5\u6e7e\u9020\u6210\u4e86\u73ca\u745a\u793c\u7901\u7834\u574f\uff0c\u8239\u9519\u76f4\u63a5\u632f\u6bc1\u73ca\u745a\u793c\u7901\u3002\u65c5\u6e38\u8239\u53ea\u548c\u6e38\u5ba2\u4ea7\u751f\u7684\u5851\u6599\u5783\u573e\u5728\u6d77\u6c34\u548c\u6c99\u6ee9\u4e0a\u5806\u79ef\u3002\u6e7e\u5185\u5927\u91cf\u8239\u53ea\u6270\u4e71\u4e86\u6d77\u6d0b\u751f\u6001\u7cfb\u7edf\u3002\u603b\u4f53\u800c\u8a00\uff0c\u4f7f\u739b\u96c5\u6e7e\u5177\u6709\u5438\u5f15\u529b\u7684\u81ea\u7136\u73af\u5883\u6b63\u5728\u88ab\u5176\u5438\u5f15\u7684\u65c5\u6e38\u6d3b\u52a8\u4e25\u91cd\u7834\u574f\u3002" },
          ],
        },
        {
          type: "quiz",
          qEn: "Why did Maya Bay become so famous and attract large numbers of tourists?",
          qZh: "\u739b\u96c5\u6e7e\u4e3a\u4ec0\u4e48\u5982\u6b64\u95fb\u540d\u5e76\u5438\u5f15\u5927\u91cf\u6e38\u5ba2\uff1f",
          opts: [
            { en: "It was the largest beach in Thailand", zh: "\u5b83\u662f\u6cf0\u56fd\u6700\u5927\u7684\u6d77\u6ee9" },
            { en: "It was featured in the 1999 film \u2018The Beach\u2019", zh: "\u5b83\u662f1999\u5e74\u7535\u5f71\u300a\u6d77\u6ee9\u300b\u7684\u62cd\u6444\u5730" },
            { en: "It was close to Bangkok and easy to reach", zh: "\u5b83\u9760\u8fd1\u66f2\u8c37\u4e14\u4ea4\u901a\u4fbf\u5229" },
            { en: "It was promoted by the Thai government as the top tourist site", zh: "\u88ab\u6cf0\u56fd\u653f\u5e9c\u5ba3\u4f20\u4e3a\u9876\u7ea7\u65c5\u6e38\u5730" },
          ],
          correct: 1,
          explainCorrectEn: "Correct! Maya Bay became famous after the 1999 film \u2018The Beach\u2019 was filmed there. This media exposure brought global attention and dramatically increased visitor numbers.",
          explainCorrectZh: "\u6b63\u786e\uff01\u739b\u96c5\u6e7e\u56e01999\u5e74\u7535\u5f71\u300a\u6d77\u6ee9\u300b\u5728\u6b64\u62cd\u6444\u800c\u95fb\u540d\u3002\u8fd9\u4e00\u5a92\u4f53\u66dd\u5149\u5e26\u6765\u4e86\u5168\u7403\u76ee\u5149\uff0c\u6e38\u5ba2\u4eba\u6570\u6025\u5287\u589e\u52a0\u3002",
          explainWrongEn: "Not quite. Maya Bay is not the largest beach in Thailand, it is not close to Bangkok (it is about 800 km away), and it was not specifically promoted by the government. Its fame came from the 1999 film \u2018The Beach\u2019.",
          explainWrongZh: "\u4e0d\u5bf9\u3002\u739b\u96c5\u6e7e\u4e0d\u662f\u6cf0\u56fd\u6700\u5927\u6d77\u6ee9\uff0c\u4e5f\u4e0d\u9760\u8fd1\u66f2\u8c37\uff08\u8ddd\u66f2\u8c37\u51688\u767e\u516c\u91cc\uff09\uff0c\u4e5f\u5e76\u975e\u653f\u5e9c\u7279\u522b\u5ba3\u4f20\u7684\u5730\u70b9\u3002\u5b83\u7684\u5c0f\u540d\u6e90\u4e8e1999\u5e74\u7535\u5f71\u300a\u6d77\u6ee9\u300b\u3002",
        },
      ],
    },

    /* ========== Lesson 4 ========== */
    {
      num: 4,
      badge: "A",
      title: "Koh Phi Phi and environmental change",
      titleZh: "\u8482\u8482\u5c9b\u4e0e\u73af\u5883\u53d8\u5316",
      subtitle: "Comparing photographs over time reveals how dramatically mass tourism changed Koh Phi Phi\u2019s environment.",
      subtitleZh: "\u5bf9\u6bd4\u4e0d\u540c\u65f6\u671f\u7684\u7167\u7247\uff0c\u53ef\u4ee5\u6e05\u6670\u5730\u770b\u5230\u5927\u4f17\u65c5\u6e38\u5982\u4f55\u6781\u5927\u6539\u53d8\u4e86\u8482\u8482\u5c9b\u7684\u73af\u5883\u3002",
      sections: [
        {
          type: "goals",
          items: [
            { en: "I can describe how Koh Phi Phi\u2019s environment changed between 1992 and 2022.", zh: "\u6211\u80fd\u63cf\u8ff0\u8482\u8482\u5c9b\u5728199\u5e74\u81f32022\u5e74\u95f4\u7684\u73af\u5883\u53d8\u5316\u3002" },
            { en: "I can use photographic evidence to identify signs of environmental degradation.", zh: "\u6211\u80fd\u5229\u7528\u7167\u7247\u8bc1\u636e\u8bc6\u522b\u73af\u5883\u9000\u5316\u7684\u8ff9\u8c61\u3002" },
            { en: "I can explain why the changes at Koh Phi Phi are evidence of unsustainable tourism.", zh: "\u6211\u80fd\u89e3\u91ca\u8482\u8482\u5c9b\u7684\u53d8\u5316\u4e3a\u4ec0\u4e48\u662f\u4e0d\u53ef\u6301\u7eed\u65c5\u6e38\u7684\u8bc1\u636e\u3002" },
          ],
        },
        {
          type: "intro",
          content: [
            { type: "text", en: "Comparing photographs of Koh Phi Phi taken in different years \u2014 1992, 2000, 2007, and 2022 \u2014 provides clear visual evidence of environmental change. Photo analysis is a valuable geographical skill: it allows us to see change over time in a way that statistics alone cannot show.", zh: "\u5bf9\u6bd4\u8482\u8482\u5c9b\u5728\u4e0d\u540c\u5e74\u4efd\u62cd\u6444\u7684\u7167\u7247\u2014\u20141992\u5e74\u30012000\u5e74\u3001200\u5e74\u548c2022\u5e74\u2014\u2014\u63d0\u4f9b\u4e86\u73af\u5883\u53d8\u5316\u7684\u76f4\u89c2\u8bc1\u636e\u3002\u7167\u7247\u5206\u6790\u662f\u4e00\u9879\u5b9d\u8d35\u7684\u5730\u7406\u5b66\u6280\u80fd\uff1a\u5b83\u4f7f\u6211\u4eec\u80fd\u591f\u770b\u5230\u5355\u7eaf\u7edf\u8ba1\u6570\u5b57\u65e0\u6cd5\u5448\u73b0\u7684\u968f\u65f6\u95f4\u53d1\u751f\u7684\u53d8\u5316\u3002" },
            { type: "highlight", en: "What the photographs reveal: More boats \u2014 from a handful in 1992 to hundreds by 2007 and beyond. More buildings \u2014 hotels, restaurants, and bars spreading across the island. Less vegetation \u2014 natural forest and plants replaced by tourist infrastructure. Heavier pressure on beaches and marine ecosystems \u2014 visible overcrowding, waste, and coral degradation.", zh: "\u7167\u7247\u63ed\u793a\u7684\u53d8\u5316\uff1a\u8239\u53ea\u589e\u52a0\u2014\u2014\u4ece1992\u5e74\u7684\u5fd8\u53ef\u6570\u52302007\u5e74\u53ca\u4e4b\u540e\u7684\u6570\u767e\u8247\u3002\u5efa\u7b51\u7269\u589e\u52a0\u2014\u2014\u9152\u5e97\u3001\u9910\u5385\u548c\u9152\u5409\u9065\u5e03\u5c9b\u4e0a\u3002\u690d\u88ab\u51cf\u5c11\u2014\u2014\u81ea\u7136\u68ee\u6797\u548c\u690d\u7269\u88ab\u65c5\u6e38\u8bbe\u65bd\u53d6\u4ee3\u3002\u6d77\u6ee9\u548c\u6d77\u6d0b\u751f\u6001\u7cfb\u7edf\u7684\u538b\u529b\u52a0\u5265\u2014\u2014\u53ef\u89c1\u7684\u62e5\u6324\u3001\u5783\u573e\u548c\u73ca\u745a\u793c\u7901\u9000\u5316\u3002" },
            { type: "text", en: "These changes are evidence of unsustainable tourism because they show that visitor growth was faster than the island could recover or adapt. Natural environments take years or decades to recover from damage. When forests are cleared, wildlife habitat is lost permanently. When coral reefs are destroyed, the marine food chain is disrupted. The visual record from Koh Phi Phi shows a destination being progressively damaged by the same industry that relied on its natural beauty.", zh: "\u8fd9\u4e9b\u53d8\u5316\u662f\u4e0d\u53ef\u6301\u7eed\u65c5\u6e38\u7684\u8bc1\u636e\uff0c\u56e0\u4e3a\u5b83\u4eec\u8868\u660e\u6e38\u5ba2\u589e\u957f\u7684\u901f\u5ea6\u8fdc\u8d85\u8fc7\u4e86\u5c9b\u5c7f\u7684\u6062\u590d\u6216\u9002\u5e94\u80fd\u529b\u3002\u81ea\u7136\u73af\u5883\u9700\u8981\u591a\u5e74\u751a\u81f3\u51e0\u5341\u5e74\u624d\u80fd\u4ece\u635f\u5bb3\u4e2d\u6062\u590d\u3002\u5f53\u68ee\u6797\u88ab\u781f\u4f10\uff0c\u91ce\u751f\u52a8\u7269\u680f\u606f\u5730\u6c38\u4e45\u4e27\u5931\u3002\u5f53\u73ca\u745a\u793c\u7901\u88ab\u6bc1\uff0c\u6d77\u6d0b\u98df\u7269\u94fe\u5c31\u4f1a\u53d7\u5230\u5e72\u6270\u3002\u8482\u8482\u5c9b\u7684\u89c6\u89c9\u8bb0\u5f55\u5c55\u793a\u4e86\u4e00\u4e2a\u76ee\u7684\u5730\u6b63\u5728\u88ab\u4f9d\u8d56\u5176\u81ea\u7136\u7f8e\u666f\u7684\u540c\u4e00\u4e1a\u4e16\u900f\u6b65\u6bc1\u574f\u3002" },
          ],
        },
        {
          type: "vocab",
          words: [
            { en: "Environmental degradation", zh: "\u73af\u5883\u9000\u5316", defEn: "The deterioration of the natural environment caused by human activity.", defZh: "\u7531\u4eba\u7c7b\u6d3b\u52a8\u5bfc\u81f4\u7684\u81ea\u7136\u73af\u5883\u6076\u5316\u3002" },
            { en: "Photo analysis", zh: "\u7167\u7247\u5206\u6790", defEn: "Using photographs as geographical evidence to identify change over time or between locations.", defZh: "\u5c06\u7167\u7247\u4f5c\u4e3a\u5730\u7406\u5b66\u8bc1\u636e\uff0c\u7528\u4e8e\u8bc6\u522b\u968f\u65f6\u95f4\u6216\u5730\u70b9\u4e4b\u95f4\u53d1\u751f\u7684\u53d8\u5316\u3002" },
            { en: "Carrying capacity", zh: "\u627f\u8f7d\u80fd\u529b", defEn: "The maximum number of visitors a destination can receive without causing unacceptable environmental or social damage.", defZh: "\u4e00\u4e2a\u76ee\u7684\u5730\u5728\u4e0d\u9020\u6210\u4e0d\u53ef\u63a5\u53d7\u7684\u73af\u5883\u6216\u793e\u4f1a\u635f\u5bb3\u7684\u524d\u63d0\u4e0b\u53ef\u63a5\u5f85\u7684\u6700\u5927\u6e38\u5ba2\u4eba\u6570\u3002" },
            { en: "Marine ecosystem", zh: "\u6d77\u6d0b\u751f\u6001\u7cfb\u7edf", defEn: "The community of living organisms and their physical environment in the ocean.", defZh: "\u6d77\u6d0b\u4e2d\u751f\u7269\u7fa4\u843d\u53ca\u5176\u7269\u7406\u73af\u5883\u7684\u603b\u7cfb\u3002" },
          ],
        },
        { type: "image", caption: "Comparative photographs of Koh Phi Phi showing environmental change from 1992 to 2022.", captionZh: "\u8482\u8482\u5c9b\u5bf9\u6bd4\u7167\u7247\uff0c\u5c55\u793a1992\u5e74\u81f32022\u5e74\u7684\u73af\u5883\u53d8\u5316\u3002", source: "Placeholder \u2014 image to be added" },
        { type: "source", labelEn: "Photographic Evidence: Koh Phi Phi", labelZh: "\u7167\u7247\u8bc1\u636e\uff1a\u8482\u8482\u5c9b", en: "Photographs of Koh Phi Phi from 1992, 2000, 2007, and 2022 show increasing numbers of boats and buildings, loss of vegetation, and heavier pressure on beaches and marine ecosystems. This visual evidence shows that tourist growth exceeded the island\u2019s carrying capacity.", zh: "\u8482\u8482\u5c9b\u57281992\u5e74\u30012000\u5e74\u3001200\u5e74\u548c2022\u5e74\u7684\u7167\u7247\u663e\u793a\u8239\u53ea\u548c\u5efa\u7b51\u7269\u4e0d\u65ad\u589e\u52a0\u3001\u690d\u88ab\u51cf\u5c11\u3001\u6d77\u6ee9\u548c\u6d77\u6d0b\u751f\u6001\u7cfb\u7edf\u9762\u4e34\u66f4\u5927\u538b\u529b\u3002\u8fd9\u4e9b\u76f4\u89c2\u8bc1\u636e\u8868\u660e\u65c5\u6e38\u589e\u957f\u8d85\u8fc7\u4e86\u8be5\u5c9b\u5c7f\u7684\u627f\u8f7d\u80fd\u529b\u3002" },
        {
          type: "think",
          questions: [
            { qEn: "Describe two visible changes to Koh Phi Phi\u2019s environment between 1992 and 2022.", qZh: "\u63cf\u8ff0\u8482\u8482\u5c9b\u5728199\u5e74\u81f32022\u5e74\u95f4\u73af\u5883\u7684\u4e24\u4e2a\u663e\u8457\u53d8\u5316\u3002", aEn: "First, the number of boats visible in the bay increased dramatically \u2014 from a handful in 1992 to hundreds by 2007, showing a huge increase in visitor numbers arriving by sea. Second, natural vegetation was replaced by tourist buildings such as hotels, restaurants, and bars, reducing the island\u2019s natural forest cover and wildlife habitat.", aZh: "\u7b2c\u4e00\uff0c\u6e7e\u5185\u53ef\u89c1\u7684\u8239\u53ea\u6570\u91cf\u6025\u5287\u589e\u52a0\u2014\u2014\u4ece1992\u5e74\u7684\u5fd8\u53ef\u6570\u52302007\u5e74\u7684\u6570\u767e\u8247\uff0c\u8868\u660e\u4e58\u8239\u62b5\u8fbe\u7684\u6e38\u5ba2\u6025\u5267\u589e\u52a0\u3002\u7b2c\u4e8c\uff0c\u81ea\u7136\u690d\u88ab\u88ab\u9152\u5e97\u3001\u9910\u5385\u548c\u9152\u5409\u7b49\u65c5\u6e38\u5efa\u7b51\u7269\u53d6\u4ee3\uff0c\u5c9b\u5c7f\u7684\u81ea\u7136\u68ee\u6797\u8986\u76d6\u548c\u91ce\u751f\u52a8\u7269\u680f\u606f\u5730\u5927\u5e45\u51cf\u5c11\u3002" },
            { qEn: "Why is photo analysis a useful geographical method for studying tourism\u2019s impact?", qZh: "\u4e3a\u4ec0\u4e48\u7167\u7247\u5206\u6790\u662f\u7814\u7a76\u65c5\u6e38\u5f71\u54cd\u7684\u6709\u7528\u5730\u7406\u5b66\u65b9\u6cd5\uff1f", aEn: "Photo analysis shows change visually over time, which statistics cannot do on their own. A photograph from 1992 compared with one from 2022 allows us to see directly how buildings, boats, vegetation, and beaches have changed. This makes it easier to communicate the scale of environmental change to a wider audience and to identify which aspects of the environment have been most affected.", aZh: "\u7167\u7247\u5206\u6790\u4ee5\u76f4\u89c2\u7684\u65b9\u5f0f\u5c55\u793a\u968f\u65f6\u95f4\u53d1\u751f\u7684\u53d8\u5316\uff0c\u8fd9\u662f\u5355\u7eaf\u7edf\u8ba1\u6570\u5b57\u65e0\u6cd5\u505a\u5230\u7684\u3002\u5c06199\u5e74\u7684\u7167\u7247\u4e0e2022\u5e74\u7684\u7167\u7247\u5bf9\u6bd4\uff0c\u6211\u4eec\u53ef\u4ee5\u76f4\u63a5\u770b\u5230\u5efa\u7b51\u7269\u3001\u8239\u53ea\u3001\u690d\u88ab\u548c\u6d77\u6ee9\u7684\u53d8\u5316\u3002\u8fd9\u4f7f\u5411\u66f4\u5e7f\u6cdb\u7684\u53d7\u4f17\u4f20\u8fbe\u73af\u5883\u53d8\u5316\u7684\u89c4\u6a21\u53d8\u5f97\u66f4\u52a0\u5bb9\u6613\uff0c\u5e76\u5c0f\u5316\u8bc6\u522b\u73af\u5883\u54ea\u4e9b\u65b9\u9762\u53d7\u5230\u5f71\u54cd\u6700\u5927\u3002" },
          ],
        },
        {
          type: "quiz",
          qEn: "Which of the following is shown by comparing photos of Koh Phi Phi from 1992 to 2022?",
          qZh: "\u5bf9\u6bd4\u8482\u8482\u5c9b199\u5e74\u81f32022\u5e74\u7684\u7167\u7247\uff0c\u53ef\u4ee5\u770b\u5230\u4ee5\u4e0b\u54ea\u4e2a\u53d8\u5316\uff1f",
          opts: [
            { en: "The island became less popular with tourists", zh: "\u5c9b\u5c7f\u5bf9\u6e38\u5ba2\u7684\u5438\u5f15\u529b\u51cf\u5f31" },
            { en: "Vegetation increased as conservation improved", zh: "\u968f\u7740\u4fdd\u62a4\u6539\u5584\uff0c\u690d\u88ab\u589e\u52a0" },
            { en: "The number of boats and buildings increased dramatically", zh: "\u8239\u53ea\u548c\u5efa\u7b51\u7269\u6570\u91cf\u6025\u5287\u589e\u52a0" },
            { en: "The coral reefs grew stronger due to more visitors", zh: "\u73ca\u745a\u793c\u7901\u56e0\u8fc7\u591a\u6e38\u5ba2\u800c\u53d8\u5f97\u66f4\u5065\u58ee" },
          ],
          correct: 2,
          explainCorrectEn: "Correct! Photographs show a dramatic increase in boats and buildings over time, along with loss of vegetation and increased pressure on beaches and marine ecosystems.",
          explainCorrectZh: "\u6b63\u786e\uff01\u7167\u7247\u663e\u793a\u8239\u53ea\u548c\u5efa\u7b51\u7269\u968f\u65f6\u95f4\u5927\u5e45\u589e\u52a0\uff0c\u540c\u65f6\u690d\u88ab\u51cf\u5c11\uff0c\u6d77\u6ee9\u548c\u6d77\u6d0b\u751f\u6001\u7cfb\u7edf\u7684\u538b\u529b\u4e5f\u5728\u52a0\u5265\u3002",
          explainWrongEn: "Not quite. Tourism increased, not decreased. Vegetation was lost, not gained. Coral reefs were damaged, not strengthened. The correct answer is the dramatic increase in boats and buildings.",
          explainWrongZh: "\u4e0d\u5bf9\u3002\u65c5\u6e38\u4eba\u6570\u589e\u52a0\u800c\u975e\u51cf\u5c11\u3002\u690d\u88ab\u51cf\u5c11\u800c\u975e\u589e\u52a0\u3002\u73ca\u745a\u793c\u7901\u53d7\u635f\u800c\u975e\u53d8\u5f97\u5065\u58ee\u3002\u6b63\u786e\u7b54\u6848\u662f\u8239\u53ea\u548c\u5efa\u7b51\u7269\u7684\u6025\u5267\u589e\u52a0\u3002",
        },
      ],
    },

    /* ========== Lesson 5 ========== */
    {
      num: 5,
      badge: "E",
      title: "How can tourism be made more sustainable?",
      titleZh: "\u5982\u4f55\u4f7f\u65c5\u6e38\u66f4\u52a0\u53ef\u6301\u7eed\uff1f",
      subtitle: "Ecotourism and careful management can protect natural environments while still allowing people to enjoy them \u2014 Maya Bay shows that recovery is possible.",
      subtitleZh: "\u751f\u6001\u65c5\u6e38\u548c\u7ec6\u5fc3\u7ba1\u7406\u53ef\u4ee5\u5728\u4fdd\u62a4\u81ea\u7136\u73af\u5883\u7684\u540c\u65f6\u8ba9\u4eba\u4eec\u6b23\u8d4f\u5b83\u2014\u2014\u739b\u96c5\u6e7e\u8bc1\u660e\u6062\u590d\u662f\u53ef\u80fd\u7684\u3002",
      sections: [
        {
          type: "goals",
          items: [
            { en: "I can define ecotourism and describe its features.", zh: "\u6211\u80fd\u5b9a\u4e49\u751f\u6001\u65c5\u6e38\u5e76\u63cf\u8ff0\u5176\u7279\u5f81\u3002" },
            { en: "I can compare mass tourism and ecotourism.", zh: "\u6211\u80fd\u6bd4\u8f83\u5927\u4f17\u65c5\u6e38\u548c\u751f\u6001\u65c5\u6e38\u3002" },
            { en: "I can evaluate the management of Maya Bay using evidence of ecological recovery.", zh: "\u6211\u80fd\u8fd0\u7528\u751f\u6001\u6062\u590d\u8bc1\u636e\u8bc4\u4f30\u739b\u96c5\u6e7e\u7684\u7ba1\u7406\u6548\u679c\u3002" },
          ],
        },
        {
          type: "intro",
          content: [
            { type: "text", en: "Ecotourism is tourism directed towards often threatened natural environments, intended to support conservation and observe wildlife. It differs from mass tourism in several important ways: it involves small groups rather than large crowds; profits reach local communities rather than large hotel chains; it is educational rather than purely recreational; and it uses basic rather than highly intensive facilities.", zh: "\u751f\u6001\u65c5\u6e38\u662f\u9488\u5bf9\u5e38\u53d7\u5a01\u80c1\u7684\u81ea\u7136\u73af\u5883\u7684\u65c5\u6e38\uff0c\u65e8\u5728\u652f\u6301\u4fdd\u62a4\u5e76\u89c2\u5bdf\u91ce\u751f\u52a8\u7269\u3002\u5b83\u4e0e\u5927\u4f17\u65c5\u6e38\u6709\u51e0\u4e2a\u91cd\u8981\u533a\u522b\uff1a\u6d89\u53ca\u5c0f\u56e2\u4f53\u800c\u975e\u5927\u89c4\u6a21\u4eba\u6d41\uff1b\u5229\u6da6\u6d41\u5165\u5f53\u5730\u793e\u533a\u800c\u975e\u5927\u578b\u9152\u5e97\u8fde\u9501\uff1b\u5177\u6709\u6559\u80b2\u610f\u4e49\u800c\u975e\u7eaf\u5c72\u6d88\u9063\uff1b\u4f7f\u7528\u57fa\u672c\u8bbe\u65bd\u800c\u975e\u5f3a\u5ea6\u5f00\u53d1\u7684\u8bbe\u65bd\u3002" },
            { type: "highlight", en: "Features of ecotourism: profits reaching local people; employing local people; strengthening mountain or rural communities; community-led programmes; small tourist groups; educational experiences; local food; teaching traditional crafts and life skills; basic rather than highly intensive facilities.", zh: "\u751f\u6001\u65c5\u6e38\u7684\u7279\u5f81\uff1a\u5229\u6da6\u6d41\u5165\u5f53\u5730\u5c45\u6c11\uff1b\u96c7\u7528\u5f53\u5730\u4eba\uff1b\u5f3a\u5316\u5c71\u5730\u6216\u519c\u6751\u793e\u533a\uff1b\u793e\u533a\u4e3b\u5bfc\u9879\u76ee\uff1b\u5c0f\u578b\u6e38\u5ba2\u56e2\uff1b\u5177\u6709\u6559\u80b2\u610f\u4e49\u7684\u4f53\u9a8c\uff1b\u5f53\u5730\u98df\u7269\uff1b\u4f20\u6388\u4f20\u7edf\u6280\u827a\u548c\u751f\u6d3b\u6280\u80fd\uff1b\u57fa\u672c\u8bbe\u65bd\u800c\u975e\u5f3a\u5ea6\u5f00\u53d1\u7684\u5efa\u7b51\u3002" },
            { type: "text", en: "Maya Bay was closed in June 2018 to allow environmental recovery. The reopening was delayed until January 2022 to allow more time for the ecosystem to heal. Evidence of recovery after closure: reef sharks and ghost crabs returned to the bay; over 23,000 corals planted by officials began to grow. This shows that active management and enforced closures can make tourism more sustainable and allow damaged ecosystems to recover.", zh: "\u739b\u96c5\u6e7e\u4e8e2018\u5e746\u6708\u5173\u95ed\u4ee5\u5141\u8bb8\u73af\u5883\u6062\u590d\u3002\u91cd\u5f00\u65f6\u95f4\u63a8\u8fdf\u81f32022\u5e741\u6708\uff0c\u4ee5\u7ed9\u751f\u6001\u7cfb\u7edf\u66f4\u591a\u7684\u6108\u5408\u65f6\u95f4\u3002\u5173\u95ed\u540e\u7684\u6062\u590d\u8bc1\u636e\uff1a\u73ca\u745a\u9cb2\u548c\u5c4c\u7b2c\u87f9\u91cd\u8fd4\u6e7e\u533a\uff1b\u5b98\u5458\u79cd\u690d\u7684\u8d852.3\u4e07\u682e\u73ca\u745a\u5f00\u59cb\u751f\u957f\u3002\u8fd9\u8bf4\u660e\uff0c\u79ef\u6781\u7684\u7ba1\u7406\u548c\u5f3a\u5236\u5c01\u9501\u53ef\u4ee5\u4f7f\u65c5\u6e38\u66f4\u52a0\u53ef\u6301\u7eed\uff0c\u5e76\u4f7f\u53d7\u635f\u7684\u751f\u6001\u7cfb\u7edf\u5f97\u5230\u6062\u590d\u3002" },
            { type: "example", en: "Ecotourism examples in Asia: Bangkok Tree House (Thailand) \u2014 uses solar power, employs local people, and is designed around nature. Keemala (Phuket, Thailand) \u2014 a luxury eco-resort integrating natural surroundings into its design. Sapana Lodge (Nepal) \u2014 a community-run lodge where profits directly support local families and conservation programmes.", zh: "\u4e9a\u6d32\u751f\u6001\u65c5\u6e38\u793a\u4f8b\uff1a\u66f2\u8c37\u6811\u5c4b\uff08\u6cf0\u56fd\uff09\u2014\u2014\u4f7f\u7528\u592a\u9633\u80fd\u3001\u96c7\u7528\u5f53\u5730\u4eba\u5e76\u4ee5\u81ea\u7136\u4e3a\u4e2d\u5fc3\u8fdb\u884c\u8bbe\u8ba1\u3002\u5409\u7801\u62c9\u5ea6\u5047\u5c4c\uff08\u6cf0\u56fd\u666e\u5409\uff09\u2014\u2014\u5c06\u81ea\u7136\u74af\u5883\u878d\u5165\u8bbe\u8ba1\u7684\u8c6a\u534e\u751f\u6001\u5ea6\u5047\u5dd1\u3002\u5c71\u4e18\u5c0f\u5c4b\uff08\u5c3c\u6cca\u5c14\uff09\u2014\u2014\u793e\u533a\u7ba1\u7406\u7684\u5c0f\u5c4b\uff0c\u5229\u6da6\u76f4\u63a5\u652f\u6301\u5f53\u5730\u5bb6\u5ead\u548c\u4fdd\u62a4\u9879\u76ee\u3002" },
          ],
        },
        {
          type: "vocab",
          words: [
            { en: "Ecotourism", zh: "\u751f\u6001\u65c5\u6e38", defEn: "Tourism directed towards threatened natural environments that aims to support conservation and observe wildlife.", defZh: "\u9488\u5bf9\u53d7\u5a01\u80c1\u7684\u81ea\u7136\u73af\u5883\u3001\u65e8\u5728\u652f\u6301\u4fdd\u62a4\u5e76\u89c2\u5bdf\u91ce\u751f\u52a8\u7269\u7684\u65c5\u6e38\u3002" },
            { en: "Conservation", zh: "\u4fdd\u62a4", defEn: "The protection and careful management of the natural environment.", defZh: "\u5bf9\u81ea\u7136\u73af\u5883\u7684\u4fdd\u62a4\u548c\u7ec6\u5fc3\u7ba1\u7406\u3002" },
            { en: "Ecological recovery", zh: "\u751f\u6001\u6062\u590d", defEn: "The return of species and habitats to an area after damage or disturbance has been reduced.", defZh: "\u635f\u5bb3\u6216\u5e72\u6270\u51cf\u5c11\u540e\uff0c\u7269\u79cd\u548c\u680f\u606f\u5730\u91cd\u8fd4\u67d0\u4e00\u5730\u533a\u7684\u8fc7\u7a0b\u3002" },
            { en: "Management", zh: "\u7ba1\u7406", defEn: "The control and organisation of visitor numbers and activities to reduce environmental impact.", defZh: "\u5bf9\u6e38\u5ba2\u4eba\u6570\u548c\u6d3b\u52a8\u8fdb\u884c\u63a7\u5236\u548c\u7ec4\u7ec7\uff0c\u4ee5\u51cf\u5c11\u73af\u5883\u5f71\u54cd\u3002" },
          ],
        },
        { type: "image", caption: "Maya Bay after its closure and ecological recovery, showing the return of marine life.", captionZh: "\u739b\u96c5\u6e7e\u5173\u95ed\u548c\u751f\u6001\u6062\u590d\u540e\uff0c\u5c55\u793a\u6d77\u6d0b\u751f\u7269\u7684\u56de\u5f52\u3002", source: "Placeholder \u2014 image to be added" },
        { type: "source", labelEn: "Case Study: Maya Bay Closure and Recovery", labelZh: "\u6848\u4f8b\u7814\u7a76\uff1a\u739b\u96c5\u6e7e\u5c01\u9501\u4e0e\u6062\u590d", en: "Maya Bay closed in June 2018 and reopened in January 2022. Evidence of recovery: reef sharks and ghost crabs returned; over 23,000 corals planted by officials began to grow. This proves that enforced management can allow ecosystems to recover from tourism damage.", zh: "\u739b\u96c5\u6e7e\u4e8e2018\u5e746\u6708\u5c01\u9501\uff0c2022\u5e741\u6708\u91cd\u5f00\u3002\u6062\u590d\u8bc1\u636e\uff1a\u73ca\u745a\u9cb2\u548c\u5c4c\u7b2c\u87f9\u91cd\u8fd4\uff1b\u5b98\u5458\u79cd\u690d\u76842.3\u4e07\u682e\u73ca\u745a\u5f00\u59cb\u751f\u957f\u3002\u8fd9\u8bc1\u660e\u5f3a\u5236\u7ba1\u7406\u53ef\u4ee5\u4f7f\u751f\u6001\u7cfb\u7edf\u4ece\u65c5\u6e38\u635f\u5bb3\u4e2d\u6062\u590d\u3002" },
        {
          type: "think",
          questions: [
            { qEn: "Compare ecotourism and mass tourism. Give two differences.", qZh: "\u6bd4\u8f83\u751f\u6001\u65c5\u6e38\u548c\u5927\u4f17\u65c5\u6e38\uff0c\u5217\u51fa\u4e24\u70b9\u4e0d\u540c\u3002", aEn: "First, ecotourism involves small groups of visitors with an educational focus, whereas mass tourism involves large numbers of tourists primarily seeking leisure and recreation. Second, ecotourism aims for profits to reach local communities, whereas mass tourism often sees profits flow to large hotel chains and international companies in the source country.", aZh: "\u7b2c\u4e00\uff0c\u751f\u6001\u65c5\u6e38\u6d89\u53ca\u5c0f\u578b\u6e38\u5ba2\u56e2\uff0c\u6ce8\u91cd\u6559\u80b2\uff0c\u800c\u5927\u4f17\u65c5\u6e38\u6d89\u53ca\u5927\u91cf\u4ee5\u4f11\u95f2\u548c\u5a31\u4e50\u4e3a\u4e3b\u8981\u76ee\u7684\u7684\u6e38\u5ba2\u3002\u7b2c\u4e8c\uff0c\u751f\u6001\u65c5\u6e38\u65e8\u5728\u5c06\u5229\u6da6\u7559\u5728\u5f53\u5730\u793e\u533a\uff0c\u800c\u5927\u4f17\u65c5\u6e38\u7684\u5229\u6da6\u5f80\u5f80\u6d41\u5411\u6765\u6e90\u56fd\u7684\u5927\u578b\u9152\u5e97\u8fde\u9501\u548c\u8de8\u56fd\u516c\u53f8\u3002" },
            { qEn: "Use evidence from Maya Bay to evaluate whether tourism can be managed sustainably.", qZh: "\u5229\u7528\u739b\u96c5\u6e7e\u7684\u8bc1\u636e\uff0c\u8bc4\u4f30\u65c5\u6e38\u662f\u5426\u53ef\u4ee5\u5f97\u5230\u53ef\u6301\u7eed\u7684\u7ba1\u7406\u3002", aEn: "The evidence from Maya Bay suggests that tourism can be managed sustainably, but only with strict intervention. After the bay was closed in 2018, reef sharks and ghost crabs returned and over 23,000 corals began to grow by 2022. This proves that ecosystems can recover when visitor pressure is removed. However, the damage took decades to accumulate and required over three years of closure to begin recovering \u2014 showing that prevention is far better than cure.", aZh: "\u739b\u96c5\u6e7e\u7684\u8bc1\u636e\u8868\u660e\uff0c\u65c5\u6e38\u53ef\u4ee5\u5f97\u5230\u53ef\u6301\u7eed\u7684\u7ba1\u7406\uff0c\u4f46\u9700\u8981\u4e25\u683c\u5e72\u9884\u3002\u8be5\u6e7e2018\u5e74\u5c01\u9501\u540e\uff0c\u73ca\u745a\u9cb2\u548c\u5c4c\u7b2c\u87f9\u91cd\u8fd4\uff0c\u52302022\u5e74\u5df2\u67092.3\u4e07\u682e\u73ca\u745a\u5f00\u59cb\u751f\u957f\u3002\u8fd9\u8bc1\u660e\uff0c\u5f53\u6e38\u5ba2\u538b\u529b\u89e3\u9664\u540e\uff0c\u751f\u6001\u7cfb\u7edf\u53ef\u4ee5\u6062\u590d\u3002\u7136\u800c\uff0c\u635f\u5bb3\u7684\u79ef\u7d2f\u5386\u65f6\u51e0\u5341\u5e74\uff0c\u5e76\u9700\u8981\u4e09\u5e74\u591a\u5c01\u9501\u624d\u5f00\u59cb\u6062\u590d\u2014\u2014\u8fd9\u8bf4\u660e\u9884\u9632\u8fdc\u80dc\u4e8e\u6cbb\u7597\u3002" },
          ],
        },
        {
          type: "quiz",
          qEn: "Which of the following best describes ecotourism?",
          qZh: "\u4ee5\u4e0b\u54ea\u9879\u6700\u80fd\u63cf\u8ff0\u751f\u6001\u65c5\u6e38\uff1f",
          opts: [
            { en: "Large-scale tourism at popular beach resorts that maximises visitor numbers", zh: "\u5728\u70ed\u95e8\u6d77\u6ee8\u5ea6\u5047\u5c71\u5e84\u8fdb\u884c\u7684\u5927\u89c4\u6a21\u65c5\u6e38\uff0c\u4ee5\u6700\u5927\u5316\u6e38\u5ba2\u6570\u91cf\u4e3a\u76ee\u6807" },
            { en: "Tourism directed at natural environments in small groups, supporting conservation and local communities", zh: "\u5c0f\u578b\u56e2\u4f53\u5c55\u5f00\u7684\u81ea\u7136\u73af\u5883\u65c5\u6e38\uff0c\u652f\u6301\u4fdd\u62a4\u5de5\u4f5c\u548c\u5f53\u5730\u793e\u533a" },
            { en: "Tourism organised by large international hotel chains in developing countries", zh: "\u7531\u5927\u578b\u8de8\u56fd\u9152\u5e97\u96c6\u56e2\u5728\u53d1\u5c55\u4e2d\u56fd\u5bb6\u7ec4\u7ec7\u7684\u65c5\u6e38" },
            { en: "Any form of tourism that avoids using aeroplanes", zh: "\u4efb\u4f55\u4e0d\u4f7f\u7528\u98de\u673a\u7684\u65c5\u6e38\u5f62\u5f0f" },
          ],
          correct: 1,
          explainCorrectEn: "Correct! Ecotourism is tourism directed towards natural environments, usually in small groups, that aims to support conservation and benefit local communities rather than send profits to large international companies.",
          explainCorrectZh: "\u6b63\u786e\uff01\u751f\u6001\u65c5\u6e38\u662f\u9488\u5bf9\u81ea\u7136\u73af\u5883\u7684\u65c5\u6e38\uff0c\u901a\u5e38\u4ee5\u5c0f\u578b\u56e2\u4f53\u5f00\u5c55\uff0c\u65e8\u5728\u652f\u6301\u4fdd\u62a4\u5e76\u60e0\u53ca\u5f53\u5730\u793e\u533a\uff0c\u800c\u975e\u5c06\u5229\u6da6\u6d41\u5411\u5927\u578b\u8de8\u56fd\u516c\u53f8\u3002",
          explainWrongEn: "Not quite. Large-scale beach tourism, hotel chains, and avoiding planes are not what defines ecotourism. The key features are: small groups, natural environments, support for conservation, and profits reaching local communities.",
          explainWrongZh: "\u4e0d\u5bf9\u3002\u5927\u89c4\u6a21\u6d77\u6ee9\u65c5\u6e38\u3001\u9152\u5e97\u96c6\u56e2\u548c\u907f\u514d\u4e58\u98de\u673a\u90fd\u4e0d\u662f\u751f\u6001\u65c5\u6e38\u7684\u5b9a\u4e49\u3002\u5173\u952e\u7279\u5f81\u662f\uff1a\u5c0f\u578b\u56e2\u4f53\u3001\u81ea\u7136\u73af\u5883\u3001\u652f\u6301\u4fdd\u62a4\u5de5\u4f5c\u4e14\u5229\u6da6\u6d41\u5165\u5f53\u5730\u793e\u533a\u3002",
        },
      ],
    },

  ],
};

export default tourism;
